Add a missing include when using C++23 or C++26.
The code compiled with older C++ standards, but when C++23 or C++26
was selected, an error was reported:
error: invalid application of 'sizeof' to an incomplete type 'Cell'.

Now it works even with C++26.
C++14 is still supported, C++20 is used by default.