Revert "A try to make "git diff" work with wxmx files"
This reverts commit 400bf79c76c6b5bb7fa009eb6b4f2a15805f20a7.

I assume, that that commit breaks the nightly build. After a checkout
some wxmx files are modified automatically, e.g.

[ 83%] Performing update step for 'wxmaxima-git'
warning: CRLF will be replaced by LF in art/draw/DrawExamples.wxmx.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in info/cell-example.wxmx.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in test/automatic_test_files/all-celltypes.wxmx.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in test/testbench_simple.wxmx.
The file will have its original line endings in your working directory
fatal: No rebase in progress?
error: Your local changes to the following files would be overwritten by merge:
	test/testbench_simple.wxmx
Please commit your changes or stash them before you merge.
Aborting

And this (probably) breaks the automatic build procedure.
wxmx files are zip files, so not text files, but binary files.