When using wxWidgets 3.1.6: Use wxWidgets nanosvg implementaion only for Windows.
For Linux builds with 3.1.6 I get linking errors, e.g.:
undefined reference to `nsvgRasterize'

Therefore do not define NANOSVG_IMPLEMENTATION/NANOSVGRAST_IMPLEMENTATION only for Windows.
That is probably not correct (a FIXME), but I have no idea, why Linux still requires
that NANOSVG_IMPLEMENTATION/NANOSVGRAST_IMPLEMENTATION is defined.